### ISSUE TITLE
handle activate stack errors

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-command-line#167] opened 2020-02-07 18:29 UTC
if you deactivate and then sync nodejs 0.2.6 currently it fails like this 

"activate stacks": [
        {
            "name": "nodejs",
            "versions": [
                {
                    "version": "0.3.1"
                },
                {
                    "version": "0.2.6"
                }
            ],
            "status": "failed to activate",
            "exception": "Internal Server Error, cause: null" 
        }
But message is not handled

**Comment by davco01a** [comment] 2020-02-12 17:52
dupe of https://github.com/kabanero-io/kabanero-command-line/issues/171

**Closed by davco01a** 2020-02-12 17:52 UTC
