### ISSUE TITLE
Create the Kabanero Management CLI for Collections and Hub Management

### ISSUE THREAD

**Issue by nateziemann** [kabanero-io/kabanero-command-line#33] opened 2019-06-21 13:30 UTC

**Comment by stephenkinder** [comment] 2019-09-10 17:59
@tseelbach if this not a dashboard or website feature, do you feel this a duplicate of the Epic for the initial drop of the CLI microservice? If so can you close it?

**Comment by davco01a** [comment] 2019-09-23 22:03
This seems like a dupe, we should probably cose it @tseelbach

**Comment by s1cyan** [comment] 2020-01-08 15:56
the cli is created

**Closed by s1cyan** 2020-01-08 15:56 UTC
